const products = [
  {
    id: 1,
    name: "Classic Office Chair",
    href: "#",
    imageSrc: "./public/office-chair1.png",
    imageAlt: "Office Chair in black",
    price: "$99",
    color: "Black",
  },
  {
    id: 2,
    name: "Classic Office Chair",
    href: "#",
    imageSrc: "./public/office-chair2.png",
    imageAlt: "Office Chair in grey",
    price: "$99",
    color: "Grey",
  },
  {
    id: 3,
    name: "Premium Office Chair",
    href: "#",
    imageSrc: "./public/office-chair3.png",
    imageAlt: "Office Chair in beige/white",
    price: "$199",
    color: "Beige/White",
  },
  {
    id: 4,
    name: "Elite Office Chair",
    href: "#",
    imageSrc: "./public/office-chair4.png",
    imageAlt: "Office Chair in beige",
    price: "$249",
    color: "Beige",
  },
  {
    id: 5,
    name: "Classic Work Desk",
    href: "#",
    imageSrc: "./public/standingdesk-white.png",
    imageAlt: "Adjustable Desk in white.",
    price: "$199",
    color: "Black",
  },
  {
    id: 6,
    name: "Adjustable Work Desk",
    href: "#",
    imageSrc: "./public/cornerdesk-white.png",
    imageAlt: "Corner Left Adjustable Desk in white.",
    price: "$249",
    color: "White Oak",
  },
  {
    id: 7,
    name: "Adjustable Work Desk",
    href: "#",
    imageSrc: "./public/cornerdesk-black.png",
    imageAlt: "Corner Left Adjustable Desk in black.",
    price: "$249",
    color: "Black Ashe",
  },
  {
    id: 8,
    name: "Heavy Adjustable Work Desk",
    href: "#",
    imageSrc: "./public/standingdesk-black.png",
    imageAlt: "Heavy Duty Adjustable Desk in black.",
    price: "$349",
    color: "Black",
  },
  {
    id: 9,
    name: "Classic Workstation",
    href: "#",
    imageSrc: "./public/workstation-corner.png",
    imageAlt: "Desk Mat in white.",
    price: "$249",
    color: "White",
  },
  {
    id: 10,
    name: "Classic Workstation",
    href: "#",
    imageSrc: "./public/workstation-cornerblack.png",
    imageAlt: "Desk Mat in white.",
    price: "$249",
    color: "Black",
  },
  {
    id: 11,
    name: "Prime Workstation",
    href: "#",
    imageSrc: "./public/workstation-linear.png",
    imageAlt: "Desk Mat in white.",
    price: "$349",
    color: "White",
  },
  {
    id: 12,
    name: "Elite Prime Workstation",
    href: "#",
    imageSrc: "./public/workstation-compact.png",
    imageAlt: "Desk Mat in white.",
    price: "$499",
    color: "Black",
  },
  {
    id: 13,
    name: "Classic Table Lamp",
    href: "#",
    imageSrc: "./public/lamp-classic.png",
    imageAlt: "Table Lamp",
    price: "$29",
    color: "White",
  },
  {
    id: 14,
    name: "Steel Table Lamp",
    href: "#",
    imageSrc: "./public/lamp-serie2.png",
    imageAlt: "Table Lamp in silver",
    price: "$39",
    color: "Silver",
  },
  {
    id: 15,
    name: "Wooden Table Lamp",
    href: "#",
    imageSrc: "./public/lamp-serie3.png",
    imageAlt: "Table Lamp in wood.",
    price: "$39",
    color: "Brown",
  },
  {
    id: 16,
    name: "Glass Table Lamp",
    href: "#",
    imageSrc: "./public/lamp-special.png",
    imageAlt: "Table Lamp in glass.",
    price: "$49",
    color: "Brown",
  },
];
export default products;
